### PR TITLE
Add stub for members test in groups

### PR DESCRIPTION
**Pull request by shakaran**
A stub for continue advancing in the unit test for members

### CODE REVIEW

**Comment by austinpapp** [comment]
which pr is this testing?

**Comment by shakaran** [comment]
@austinpapp yes, this is for testing the members new API part. Just a stub, not fully implemented all entry points and params

**Comment by austinpapp** [comment]
ah ok. got it. 

fyi - i think i may merge this repo into server. bummer its not PHP but whatever. its easy enough to run `python -m unittest discover test "*_test.py"`

**Comment by austinpapp** [comment]
also, we may need to swing back to this one just to partially hydrate the db just to get a good 200 response with data (obviously the same data response every time). however, this is good for now. thanks

**Pull request merged**
